apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::830895970124:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
        - system:masters
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::830895970124:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-YJ0PNGIV75US
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-07-08T21:46:18Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "851"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: b2265bd0-b017-4b09-87ef-248416fe70bb
